abstract class AfeerState{}
class InitState extends AfeerState{}
class CreateUserSuccessfully extends AfeerState{}
class CreateUserFailed extends AfeerState{}
class LoginUserSuccessfully extends AfeerState{}
class LoginUserFailed extends AfeerState{}
class TogglePasswordVisibility extends AfeerState{}
class ChangePasswordSuccessfully extends AfeerState{}
class ChangePasswordFailed extends AfeerState{}
class CreateSubjectSuccessfully extends AfeerState{}
class CreateSubjectFailed extends AfeerState{}
class UploadVideoSuccessfully extends AfeerState{}
class UploadVideoFailed extends AfeerState{}
class UploadPdfSuccessfully extends AfeerState{}
class UploadPdfFailed extends AfeerState{}
class UploadPhotoSuccessfully extends AfeerState{}
class UploadPhotoFailed extends AfeerState{}
class UploadTeacherPhotoSuccessfully extends AfeerState{}
class UploadTeacherPhotoFailed extends AfeerState{}
class GetVideoSuccessfully extends AfeerState{}
class GetVideoFailed extends AfeerState{}
class GetPdfSuccessfully extends AfeerState{}
class GetPdfFailed extends AfeerState{}
class GetPhotoSuccessfully extends AfeerState{}
class GetPhotoFailed extends AfeerState{}
class ChooseColors extends AfeerState{}
class ChangeAccess extends AfeerState{}
class TogglePaidSuccessfully extends AfeerState{}
class CreateLectureSuccessfully extends AfeerState{}
class CreateLectureFailed extends AfeerState{}
class UploadVideoLoading extends AfeerState{}
class SecureDataSuccessfully extends AfeerState{}
class SecureDataFailed extends AfeerState{}
class ForgetPasswordSuccessfully extends AfeerState{}
class ForgetPasswordFailed extends AfeerState{}
class CreateNewBarCodeSuccessfully extends AfeerState{}
class CreateNewBarCodeFailed extends AfeerState{}
class DeleteSubjectSuccessfully extends AfeerState{}
class DeleteSubjectFailed extends AfeerState{}
class DeleteLectureFailed extends AfeerState{}
class GetAllUserSuccessfully extends AfeerState{}
class GetAllUserFailed extends AfeerState{}
class ChangeValueSuccessfully extends AfeerState{}

